"""
SQLAlchemy models defining the persistence layer for the AI Blog Generator.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import Column, DateTime, Integer, String, Text
from sqlalchemy.orm import declarative_base


Base = declarative_base()


class Blog(Base):
    """
    Represents a generated blog article stored in the local SQLite database.

    Attributes:
        id: Primary key identifier for the blog entry.
        title: Title or topic supplied by the user.
        content: Generated blog body (Markdown/HTML friendly text).
        tone: Optional tone specification used for generation.
        created_at: Timestamp when the blog was first generated.
        updated_at: Timestamp of the most recent regeneration.
    """

    __tablename__ = "blogs"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(255), nullable=False)
    content = Column(Text, nullable=False)
    tone = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    def update_content(self, new_content: str) -> None:
        """
        Overwrite the blog content and refresh the ``updated_at`` timestamp.

        Args:
            new_content: Replacement text generated by the AI service.
        """

        self.content = new_content
        self.updated_at = datetime.utcnow()


